### ISSUE TITLE
typo in textbook

### ISSUE THREAD

**Issue by naiborhujosua** [PacktPublishing/Interpretable-Machine-Learning-with-Python#13]
ROC-AUC curve that was  explained on page 81 by plotting  the proportion of true 
positive rate (Recall) on the x-axis and the false positive rate on the y-axis should be 
plotting the proportion of the true positive rate (Recall) on the y-axis and the false positive rate on the x-axis.

**Comment by smasis001** [comment]
The typo has been fixed for the second edition. Thank you for reporting it, @naiborhujosua !
