### ISSUE TITLE
Heights weights doesnt work

### ISSUE THREAD

**Issue by Eraseri** [PacktPublishing/Interpretable-Machine-Learning-with-Python#3]
Bought book. Cloned this git. First cell after importing libraries is broken. 

`url = 'http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Dinov_020108_HeightsWeights'
page = requests.get(url)`

**Comment by smasis001** [comment]
See [issue #5 ](https://github.com/PacktPublishing/Interpretable-Machine-Learning-with-Python/issues/5) as to why I'm closing this issue.
